# Site settings
title: "The SS blog"
author:
  name: Claude Bolduc
description: "Blogging about software analysis for Safety and Security (SS)"

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: solarized-light
